---
output: html_document
params:
    reviewer_first_name: "Jane"
    banter: " "
    JOSS: FALSE

---

Dear `r params$reviewer_first_name`

Hi, this is  from rOpenSci `r emo::ji("wave")`.

`r params$banter`

I'm writing to ask if you would be willing to review a package for rOpenSci.
As you probably know, rOpenSci conducts peer review of R packages contributed to our collection in a manner similar to journals.

The package is **`rredlist`** by `r 
    c(person(given = "William",
             family = "Gearty",
             role = c("aut", "cre"),
             email = "willgearty@gmail.com"),
      person(given = "Scott",
             family = "Chamberlain",
             role = c("aut"),
             email = "myrmecocystus@gmail.com"),
      person(given = "rOpenSci",
             role = "fnd",
             comment = "https://ropensci.org/"),
      person(given = "Maëlle",
             family = "Salmon",
             role = "ctb",
             email = "maelle.salmon@yahoo.se")
      )`:

> 'IUCN' Red List (<https://api.iucnredlist.org/>) client.
    The 'IUCN' Red List is a global list of threatened and endangered species.
    Functions cover all of the Red List 'API' routes. An 'API' key is required.


You can find it on GitHub [here](https://github.com/ropensci/rredlist).
We conduct our open review process via GitHub as well, [here](https://github.com/ropensci/onboarding/issues/).


If you accept, note that we ask reviewers to complete reviews in three weeks.
(We’ve found it takes a similar amount of time to review a package as an academic paper.)

Our [reviewers guide] details what we look for in a package review and includes links to example reviews.
Our standards are detailed in our [packaging guide], and we provide a reviewer [template] for you to use.
You can also use package [pkgreviewr] to help set up and guide your review.
If you have questions or feedback, feel free to ask me or post to the [rOpenSci forum].
You can also try the rOpenSci Slack community.
If you accept to review and are not already a member of the Slack community, please let me know so I can invite you.

`r if(params$JOSS){"The authors have also chosen to jointly submit their package to the Journal of Open Source Software, so this package includes a short paper.md manuscript describing the software that we ask you include in your review."}`

Are you able to review?
If you cannot, suggestions for alternate reviewers are always helpful.
If I don't hear from you within a week, I will assume you are unable to review at this time.

Thank you for your time.

Sincerely,



[reviewers guide]: https://ropensci.github.io/dev_guide/reviewerguide.html
[packaging guide]: https://ropensci.github.io/dev_guide/building.html
[template]: https://ropensci.github.io/dev_guide/reviewtemplate.html
[rOpenSci forum]: https://discuss.ropensci.org/
[pkgreviewr]: https://github.com/ropenscilabs/pkgreviewr
